"""stock_control

Revision ID: 1a976ce4a216
Revises: d4e5f6a7b8c9
Create Date: 2026-07-24 19:59:28.918867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1a976ce4a216'
down_revision: Union[str, None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_items',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('unit', sa.Enum('unit', 'kg', 'g', 'l', 'ml', name='stock_unit_enum'), nullable=False),
    sa.Column('quantity_on_hand', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('min_quantity', sa.Numeric(precision=12, scale=3), server_default='0', nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_items_deleted_at'), 'stock_items', ['deleted_at'], unique=False)
    op.create_index('ix_stock_items_establishment_active', 'stock_items', ['establishment_id', 'is_active'], unique=False)
    op.create_index(op.f('ix_stock_items_establishment_id'), 'stock_items', ['establishment_id'], unique=False)
    op.create_index(op.f('ix_stock_items_is_active'), 'stock_items', ['is_active'], unique=False)
    op.create_table('menu_item_ingredients',
    sa.Column('menu_item_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('quantity_per_unit', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('menu_item_id', 'stock_item_id', name='uq_menu_item_ingredient')
    )
    op.create_index(op.f('ix_menu_item_ingredients_menu_item_id'), 'menu_item_ingredients', ['menu_item_id'], unique=False)
    op.create_index(op.f('ix_menu_item_ingredients_stock_item_id'), 'menu_item_ingredients', ['stock_item_id'], unique=False)
    op.create_table('stock_movements',
    sa.Column('establishment_id', sa.UUID(), nullable=False),
    sa.Column('stock_item_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('purchase', 'adjustment', 'sale', 'loss', name='stock_movement_kind_enum'), nullable=False),
    sa.Column('quantity_change', sa.Numeric(precision=12, scale=3), nullable=False),
    sa.Column('reason', sa.String(length=300), nullable=True),
    sa.Column('order_item_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['establishment_id'], ['establishments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['stock_item_id'], ['stock_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_movements_establishment_id'), 'stock_movements', ['establishment_id'], unique=False)
    op.create_index('ix_stock_movements_item_created', 'stock_movements', ['stock_item_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_stock_movements_stock_item_id'), 'stock_movements', ['stock_item_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_stock_item_id'), table_name='stock_movements')
    op.drop_index('ix_stock_movements_item_created', table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_establishment_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    op.drop_index(op.f('ix_menu_item_ingredients_stock_item_id'), table_name='menu_item_ingredients')
    op.drop_index(op.f('ix_menu_item_ingredients_menu_item_id'), table_name='menu_item_ingredients')
    op.drop_table('menu_item_ingredients')
    op.drop_index(op.f('ix_stock_items_is_active'), table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_establishment_id'), table_name='stock_items')
    op.drop_index('ix_stock_items_establishment_active', table_name='stock_items')
    op.drop_index(op.f('ix_stock_items_deleted_at'), table_name='stock_items')
    op.drop_table('stock_items')
    # ### end Alembic commands ###
