"""sends_to_kitchen

Revision ID: 9434c9420e4f
Revises: e0df92b8d908
Create Date: 2026-07-24 20:39:06.791981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9434c9420e4f'
down_revision: Union[str, None] = 'e0df92b8d908'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_categories', sa.Column('sends_to_kitchen', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_categories', 'sends_to_kitchen')
    # ### end Alembic commands ###
